Aqua_Weather_Station: FixedQueueArray< T > Class Template Reference
FixedQueueArray< T > Class Template Reference
#include <FixedQueueArray.h>
Public Member Functions
FixedQueueArray ()
~FixedQueueArray ()
void enqueue (const T i)
T dequeue ()
void push (const T i)
T pop ()
T front () const
T peek () const
bool isEmpty () const
int count () const
bool isFull () const
void setPrinter (Print &p)
void resize (const int s)
Private Member Functions
void exit (const char *m) const
void exit (const __FlashStringHelper *m) const
void blink () const
Private Attributes
Print * printer
T * contents
int size
int items
int head
int tail
Static Private Attributes
static const int initialSize = 2
static const int ledPin = 13
Detailed Description
template<typename T>
class FixedQueueArray< T >
Definition at line 66 of file FixedQueueArray.h.
Constructor & Destructor Documentation
template<typename T > FixedQueueArray< T >::FixedQueueArray ()
Definition at line 136 of file FixedQueueArray.h.
template<typename T > FixedQueueArray< T >::~FixedQueueArray ()
Definition at line 158 of file FixedQueueArray.h.
Member Function Documentation
template<typename T > void FixedQueueArray< T >::blink () const private
Definition at line 323 of file FixedQueueArray.h.
template<typename T > int FixedQueueArray< T >::count () const
Definition at line 289 of file FixedQueueArray.h.
template<typename T > T FixedQueueArray< T >::dequeue ()
Definition at line 230 of file FixedQueueArray.h.
Referenced by RF_reciever::convertPulses2Bits(), and RF_reciever::resetAll().
template<typename T> void FixedQueueArray< T >::enqueue (const T i)
Definition at line 204 of file FixedQueueArray.h.
Referenced by RF_reciever::isrPinChange().
template<typename T > void FixedQueueArray< T >::exit (const char * m) const private
Definition at line 301 of file FixedQueueArray.h.
template<typename T > void FixedQueueArray< T >::exit (const __FlashStringHelper * m) const private
Definition at line 312 of file FixedQueueArray.h.
template<typename T > T FixedQueueArray< T >::front () const
Definition at line 260 of file FixedQueueArray.h.
template<typename T > bool FixedQueueArray< T >::isEmpty () const
Definition at line 277 of file FixedQueueArray.h.
Referenced by RF_reciever::convertPulses2Bits(), and RF_reciever::resetAll().
template<typename T > bool FixedQueueArray< T >::isFull () const
Definition at line 283 of file FixedQueueArray.h.
template<typename T > T FixedQueueArray< T >::peek () const
Definition at line 271 of file FixedQueueArray.h.
template<typename T > T FixedQueueArray< T >::pop ()
Definition at line 254 of file FixedQueueArray.h.
template<typename T> void FixedQueueArray< T >::push (const T i)
Definition at line 224 of file FixedQueueArray.h.
template<typename T > void FixedQueueArray< T >::resize (const int s)
Definition at line 173 of file FixedQueueArray.h.
Referenced by RF_reciever::setup().
template<typename T > void FixedQueueArray< T >::setPrinter (Print & p)
Definition at line 295 of file FixedQueueArray.h.
Referenced by RF_reciever::setPrinter().
Member Data Documentation
template<typename T> T* FixedQueueArray< T >::contents private
Definition at line 125 of file FixedQueueArray.h.
template<typename T> int FixedQueueArray< T >::head private
Definition at line 130 of file FixedQueueArray.h.
template<typename T> const int FixedQueueArray< T >::initialSize = 2 static private
Definition at line 119 of file FixedQueueArray.h.
template<typename T> int FixedQueueArray< T >::items private
Definition at line 128 of file FixedQueueArray.h.
template<typename T> const int FixedQueueArray< T >::ledPin = 13 static private
Definition at line 122 of file FixedQueueArray.h.
template<typename T> Print* FixedQueueArray< T >::printer private
Definition at line 124 of file FixedQueueArray.h.
template<typename T> int FixedQueueArray< T >::size private
Definition at line 127 of file FixedQueueArray.h.
template<typename T> int FixedQueueArray< T >::tail private
Definition at line 131 of file FixedQueueArray.h.
The documentation for this class was generated from the following file:
Libraries/FixedQueueArray/FixedQueueArray.h