Aqua_Weather_Station: RF_reciever Class Reference
RF_reciever Class Reference
#include <RFreceiver.h>
Public Member Functions
RF_reciever ()
virtual ~RF_reciever ()
void setup (int queueSize=64)
void start ()
void stop ()
bool checkForMessages ()
bool checkQueueTailForExtraMessages ()
void turnDebugON ()
void turnDebugOFF ()
void setPrinter (HardwareSerial &p)
void printMessage ()
Static Public Attributes
static int preamble = 0
static int id = 0
static bool batteryOK = false
static bool ManualTransmit = false
static int channel = 0
static int temperature10 = 0
static bool negativeTemperature = false
static int relativeHumidity = 0
static unsigned long timeMicros = 0
static unsigned int noiseCount = 0
Private Member Functions
void resetAll ()
void restart ()
void overflowCheck ()
void resetMessage ()
bool validateMessage ()
bool convertPulses2Bits ()
bool convertBitToMessage (byte currentBit)
void debugPrint (String s)
void debugPrint (const __FlashStringHelper *s)
Static Private Member Functions
static void isrPinChange ()
Private Attributes
HardwareSerial * printer
Static Private Attributes
static FixedQueueArray
< unsigned long > queueTime
static FixedQueueArray< bool > queuePinState
static bool debug = false
static volatile unsigned long lastTransitionTimeHigh = 0
static volatile unsigned long lastTransitionTimeLow = 0
static volatile int bitNumber = 0
static volatile bool interruptIsRunning = false
Detailed Description
Processes messages coming from the 433MHz receiver which is listening for signals coming from the Aqua weather station.
Definition at line 18 of file RFreceiver.h.
Constructor & Destructor Documentation
RF_reciever::RF_reciever ()
Constructor
Definition at line 43 of file RFreceiver.cpp.
References debug, INPUT_PIN, printer, and resetAll().
RF_reciever::~RF_reciever () virtual
Unused destructor
Definition at line 53 of file RFreceiver.cpp.
Member Function Documentation
bool RF_reciever::checkForMessages ()
The main loop function that checks for new messages. Call this often.
Returns
true if a valid message has been found, false otherwise
Definition at line 151 of file RFreceiver.cpp.
References convertPulses2Bits(), interruptIsRunning, overflowCheck(), start(), and stop().
bool RF_reciever::checkQueueTailForExtraMessages ()
Once the function checkForMessages() has found a valid message there may be repeats of the same messages in the queue that haven't been processed yet. This function allow the remainder of the queue to checked for repeat messages
Returns
true if another message has been found in the queue
Definition at line 171 of file RFreceiver.cpp.
References convertPulses2Bits().
bool RF_reciever::convertBitToMessage (byte currentBit) private
Parameters
currentBit a zero, one or long gap created by the convertPulses2Bits() function
Returns
true if a valid message has been found, false otherwise
Definition at line 218 of file RFreceiver.cpp.
References batteryOK, bitNumber, channel, debugPrint(), LONG_GAP, ManualTransmit, negativeTemperature, noiseCount, ONE_BIT, preamble, relativeHumidity, resetMessage(), temperature10, timeMicros, and validateMessage().
Referenced by convertPulses2Bits().
bool RF_reciever::convertPulses2Bits () private
Converts the raw data from the receiver into zeros, ones and long gaps if a pulse has been detected.
Returns
true if a valid message has been found, false otherwise.
Definition at line 341 of file RFreceiver.cpp.
References convertBitToMessage(), FixedQueueArray< T >::dequeue(), FixedQueueArray< T >::isEmpty(), lastTransitionTimeHigh, lastTransitionTimeLow, LONG_GAP, ONE_BIT, queuePinState, queueTime, and ZERO_BIT.
Referenced by checkForMessages(), and checkQueueTailForExtraMessages().
void RF_reciever::debugPrint (String s) private
Prints the string s to the serial port if debug is enabled and a serial port has been attached by the setPrinter() function.
Parameters
s A string to print to the serial port
Definition at line 429 of file RFreceiver.cpp.
References debug, and printer.
Referenced by convertBitToMessage(), printMessage(), and validateMessage().
void RF_reciever::debugPrint (const __FlashStringHelper * s) private
Overloaded debugPrint that uses the PROGMEM F() macro to be more RAM efficient
Parameters
s A string wrapped in the F() macro
Definition at line 446 of file RFreceiver.cpp.
References debug, and printer.
void RF_reciever::isrPinChange () static private
How many bits have been received by the 433MHz rx between heartbeats This function is called every time pin 7 changes. It records the time of the change and the pin polarity to queues *
Definition at line 331 of file RFreceiver.cpp.
References FixedQueueArray< T >::enqueue(), INPUT_PIN, queuePinState, and queueTime.
Referenced by start().
void RF_reciever::overflowCheck () private
Checks if the micros() timer has overflown (happens every 70min)
Definition at line 109 of file RFreceiver.cpp.
References interruptIsRunning, lastTransitionTimeHigh, resetAll(), and restart().
Referenced by checkForMessages().
void RF_reciever::printMessage ()
Prints the temperature, humidity, etc. to the serial port
Definition at line 199 of file RFreceiver.cpp.
References batteryOK, channel, debugPrint(), ManualTransmit, negativeTemperature, preamble, relativeHumidity, temperature10, and timeMicros.
Referenced by validateMessage().
void RF_reciever::resetAll () private
Clears messages and queues
Definition at line 89 of file RFreceiver.cpp.
References bitNumber, FixedQueueArray< T >::dequeue(), FixedQueueArray< T >::isEmpty(), queuePinState, queueTime, and resetMessage().
Referenced by overflowCheck(), RF_reciever(), and start().
void RF_reciever::resetMessage () private
Clears all the message data
Definition at line 313 of file RFreceiver.cpp.
References batteryOK, bitNumber, channel, ManualTransmit, negativeTemperature, preamble, relativeHumidity, temperature10, and timeMicros.
Referenced by convertBitToMessage(), and resetAll().
void RF_reciever::restart () private
Restarts the interrupt. Called if the micros() timer overflows
Definition at line 144 of file RFreceiver.cpp.
References start(), and stop().
Referenced by overflowCheck().
void RF_reciever::setPrinter (HardwareSerial & p)
Allows you to set which serial device to print debug messages to
Parameters
p a hardware serial port on your arduino (e.g. Serial1)
Definition at line 77 of file RFreceiver.cpp.
References printer, queuePinState, queueTime, and FixedQueueArray< T >::setPrinter().
void RF_reciever::setup (int queueSize = 64)
Sets the size of the signal queues that the interrupts write to. If you set these too high then the arduino runs out of RAM, too low and a full message won't be received. 64 works ok.
Parameters
queueSize how large to set the queues to be
Definition at line 57 of file RFreceiver.cpp.
References queuePinState, queueTime, and FixedQueueArray< T >::resize().
void RF_reciever::start ()
Starts the interrupt listening on pin 7
Definition at line 127 of file RFreceiver.cpp.
References INTERRUPT_NUMBER, interruptIsRunning, isrPinChange(), lastTransitionTimeHigh, lastTransitionTimeLow, and resetAll().
Referenced by checkForMessages(), and restart().
void RF_reciever::stop ()
Stops the interrupt listening on pin 7
Definition at line 137 of file RFreceiver.cpp.
References INTERRUPT_NUMBER, and interruptIsRunning.
Referenced by checkForMessages(), and restart().
void RF_reciever::turnDebugOFF ()
Turns debug OFF so that no messages are printer to the serial device defined by printer. Set this to make the program run faster.
Definition at line 72 of file RFreceiver.cpp.
References debug.
void RF_reciever::turnDebugON ()
Turns debug ON so that messages are printer to the serial device defined by printer.
Definition at line 67 of file RFreceiver.cpp.
References debug.
bool RF_reciever::validateMessage () private
Validates the message (e.g. checks temperate valid etc.)
Returns
true if the message is valid
Definition at line 176 of file RFreceiver.cpp.
References debugPrint(), preamble, printMessage(), relativeHumidity, and temperature10.
Referenced by convertBitToMessage().
Member Data Documentation
bool RF_reciever::batteryOK = false static
ID of the weather station
Definition at line 85 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), and resetMessage().
volatile int RF_reciever::bitNumber = 0 static private
Last time the interrupt pin was LOW
Definition at line 156 of file RFreceiver.h.
Referenced by convertBitToMessage(), resetAll(), and resetMessage().
int RF_reciever::channel = 0 static
If true then someone has pressed the TX button on the weather station
Definition at line 87 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), and resetMessage().
bool RF_reciever::debug = false static private
A queue to store the polarity of the interrupt pin when it fired
Definition at line 153 of file RFreceiver.h.
Referenced by debugPrint(), RF_reciever(), turnDebugOFF(), and turnDebugON().
int RF_reciever::id = 0 static
Message preamble, should be 0101 or 5
Definition at line 84 of file RFreceiver.h.
Referenced by EthernetWeather::makeJSONstring().
volatile bool RF_reciever::interruptIsRunning = false static private
The bit number of the current signal (0 to 35) - 36bits in message
Definition at line 157 of file RFreceiver.h.
Referenced by checkForMessages(), overflowCheck(), start(), and stop().
volatile unsigned long RF_reciever::lastTransitionTimeHigh = 0 static private
If printing messages to the serial is enabled or not
Definition at line 154 of file RFreceiver.h.
Referenced by convertPulses2Bits(), overflowCheck(), and start().
volatile unsigned long RF_reciever::lastTransitionTimeLow = 0 static private
Last time the interrupt pin was HIGH
Definition at line 155 of file RFreceiver.h.
Referenced by convertPulses2Bits(), and start().
bool RF_reciever::ManualTransmit = false static
Is the battery in the station OK
Definition at line 86 of file RFreceiver.h.
Referenced by convertBitToMessage(), printMessage(), and resetMessage().
bool RF_reciever::negativeTemperature = false static
The temperature in celsius multiplied by 10 (e.g. 21.5 degrees =215)
Definition at line 89 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), and resetMessage().
unsigned int RF_reciever::noiseCount = 0 static
Milliseconds since arduino started
Definition at line 92 of file RFreceiver.h.
Referenced by convertBitToMessage(), and EthernetWeather::sendHeartbeat().
int RF_reciever::preamble = 0 static
Definition at line 83 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), resetMessage(), and validateMessage().
HardwareSerial* RF_reciever::printer private
Definition at line 147 of file RFreceiver.h.
Referenced by debugPrint(), RF_reciever(), and setPrinter().
FixedQueueArray< bool > RF_reciever::queuePinState static private
A queue to store what time the interrupt function was fired
Definition at line 149 of file RFreceiver.h.
Referenced by convertPulses2Bits(), isrPinChange(), resetAll(), setPrinter(), and setup().
FixedQueueArray< unsigned long > RF_reciever::queueTime static private
A serial port on the arduino to print messages to
Definition at line 148 of file RFreceiver.h.
Referenced by convertPulses2Bits(), isrPinChange(), resetAll(), setPrinter(), and setup().
int RF_reciever::relativeHumidity = 0 static
flag to indicate temperature is less than zero
Definition at line 90 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), resetMessage(), and validateMessage().
int RF_reciever::temperature10 = 0 static
Channel unit is transmitting on (zero to three)
Definition at line 88 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), resetMessage(), and validateMessage().
unsigned long RF_reciever::timeMicros = 0 static
Relative humidity
Definition at line 91 of file RFreceiver.h.
Referenced by convertBitToMessage(), EthernetWeather::makeJSONstring(), printMessage(), and resetMessage().
The documentation for this class was generated from the following files:
RFreceiver.h
RFreceiver.cpp