Aqua_Weather_Station: EthernetWeather Class Reference
EthernetWeather Class Reference
#include <EthernetWeather.h>
Public Member Functions
EthernetWeather ()
virtual ~EthernetWeather ()
void setup ()
void turnDebugON ()
void turnDebugOFF ()
void setPrinter (HardwareSerial &p)
void sendMessage ()
void sendHeartbeat ()
Static Public Attributes
static uint8_t mac [] = {0x4E,0x50,0x48,0x5A,0x43,0x59}
static IPAddress myIP
static IPAddress dnsIP
static IPAddress gateway
static const char webServerURL [] = "arduinoTemperatureWebserver.local"
static uint16_t port = 12781
Private Member Functions
void stringIPandPort (IPAddress ip, String &dest, uint16_t port=80)
void stringURLandPort (const char *url, String &dest, uint16_t portNum=80)
void makeJSONstring ()
void debugPrint (String s)
void debugPrint (const __FlashStringHelper *s)
void connectToserver ()
Private Attributes
HardwareSerial * printer
Static Private Attributes
static EthernetClient client
static String jsonData
static bool debug = false
Detailed Description
This class sends temperature and humidity data to a web server as a JSON POST packet.
Definition at line 18 of file EthernetWeather.h.
Constructor & Destructor Documentation
EthernetWeather::EthernetWeather ()
Constructor
Definition at line 37 of file EthernetWeather.cpp.
References debug, jsonData, and printer.
EthernetWeather::~EthernetWeather () virtual
Unused destructor
Definition at line 44 of file EthernetWeather.cpp.
Member Function Documentation
void EthernetWeather::connectToserver () private
Attempts to open a connection to the web server
Definition at line 87 of file EthernetWeather.cpp.
References client, debugPrint(), port, stringURLandPort(), and webServerURL.
Referenced by sendHeartbeat(), and sendMessage().
void EthernetWeather::debugPrint (String s) private
Prints a debug messages to the serial port
Parameters
s the message to be printed
Definition at line 277 of file EthernetWeather.cpp.
References debug, and printer.
Referenced by connectToserver(), sendHeartbeat(), sendMessage(), and setup().
void EthernetWeather::debugPrint (const __FlashStringHelper * s) private
Overloaded debugPrint that uses the PROGMEM F() macro to be more RAM efficient
Parameters
s A string wrapped in the F() macro
Definition at line 297 of file EthernetWeather.cpp.
References debug, and printer.
void EthernetWeather::makeJSONstring () private
Makes a JSON string containing temperature and humidity that will be sent to the server
Definition at line 257 of file EthernetWeather.cpp.
References RF_reciever::batteryOK, RF_reciever::channel, RF_reciever::id, jsonData, RF_reciever::negativeTemperature, RF_reciever::preamble, RF_reciever::relativeHumidity, RF_reciever::temperature10, and RF_reciever::timeMicros.
Referenced by sendMessage().
void EthernetWeather::sendHeartbeat ()
Sends a JSON POST packet to a web server saying "OK" and listing how many bits the 433MHz receiver has recieved (including noise) since the last heartbeat.
Definition at line 112 of file EthernetWeather.cpp.
References client, connectToserver(), debugPrint(), RF_reciever::noiseCount, port, stringURLandPort(), and webServerURL.
void EthernetWeather::sendMessage ()
Gets the temperature and humidity data from the RF_reciever class and sends a JSON POST message to a web server
Definition at line 168 of file EthernetWeather.cpp.
References client, connectToserver(), debugPrint(), jsonData, makeJSONstring(), port, stringURLandPort(), and webServerURL.
void EthernetWeather::setPrinter (HardwareSerial & p)
Set which hardware serial port to print debug messages to
Parameters
p a hardware serial port to print debug messages to
Definition at line 81 of file EthernetWeather.cpp.
References printer.
void EthernetWeather::setup ()
Sets up the ethernet sheild by assigning it a MAC address and static IP (change these if you need)
Definition at line 48 of file EthernetWeather.cpp.
References debugPrint(), dnsIP, gateway, mac, myIP, and stringIPandPort().
void EthernetWeather::stringIPandPort (IPAddress ip, String & dest, uint16_t port = 80) private
Generates a string in the form "IP address:port"
Parameters
ip The IP address
dest the string that is passed back
port the port number
Definition at line 224 of file EthernetWeather.cpp.
Referenced by setup().
void EthernetWeather::stringURLandPort (const char * url, String & dest, uint16_t portNum = 80) private
Generates a string in the form url:port"
Parameters
url The url
dest the string that is passed back
portNum the port number
Definition at line 244 of file EthernetWeather.cpp.
Referenced by connectToserver(), sendHeartbeat(), and sendMessage().
void EthernetWeather::turnDebugOFF ()
Don't print debug messages to the serial port. Faster and saves RAM
Definition at line 76 of file EthernetWeather.cpp.
References debug.
void EthernetWeather::turnDebugON ()
Print debug messages to the serial port set by the setPrinter() function
Definition at line 71 of file EthernetWeather.cpp.
References debug.
Member Data Documentation
EthernetClient EthernetWeather::client static private
A class used to send messages to the web server
Definition at line 130 of file EthernetWeather.h.
Referenced by connectToserver(), sendHeartbeat(), and sendMessage().
bool EthernetWeather::debug = false static private
the JSON string that is sent to the web server
Definition at line 134 of file EthernetWeather.h.
Referenced by debugPrint(), EthernetWeather(), turnDebugOFF(), and turnDebugON().
IPAddress EthernetWeather::dnsIP static
The IP address of the web server to send messages to The IP address of your local DNS server (if you have one)
Definition at line 73 of file EthernetWeather.h.
Referenced by setup().
IPAddress EthernetWeather::gateway static
Internet gateway IP address
Definition at line 78 of file EthernetWeather.h.
Referenced by setup().
String EthernetWeather::jsonData static private
Definition at line 132 of file EthernetWeather.h.
Referenced by EthernetWeather(), makeJSONstring(), and sendMessage().
uint8_t EthernetWeather::mac = {0x4E,0x50,0x48,0x5A,0x43,0x59} static
The MAC address of this arduino
Definition at line 59 of file EthernetWeather.h.
Referenced by setup().
IPAddress EthernetWeather::myIP static
The static IP address of this Arduino
Definition at line 64 of file EthernetWeather.h.
Referenced by setup().
uint16_t EthernetWeather::port = 12781 static
The port the web server is running on (usually 80)
Definition at line 88 of file EthernetWeather.h.
Referenced by connectToserver(), sendHeartbeat(), and sendMessage().
HardwareSerial* EthernetWeather::printer private
If debug messages should be printed to the serial port
Definition at line 135 of file EthernetWeather.h.
Referenced by debugPrint(), EthernetWeather(), and setPrinter().
const char EthernetWeather::webServerURL = "arduinoTemperatureWebserver.local" static
URL of webserver where temperature should be logged. Use this or serverIP
Definition at line 83 of file EthernetWeather.h.
Referenced by connectToserver(), sendHeartbeat(), and sendMessage().
The documentation for this class was generated from the following files:
EthernetWeather.h
EthernetWeather.cpp